import type { Metadata } from "next";
import "./styles/index.scss";
import { NextUIProvider } from "@nextui-org/system";
import { Providers } from "../components/app/providers/providers";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
           
           <body >
           <Providers>
            {children}
           </Providers>
           </body>
           
  
    </html>
  );
}
