version: '3.8'
 
services:
   postgres:
     image: postgres:15.1
     volumes:
       - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
       - postgres_microservice_back:/var/lib/postgresql/data
     environment:
       POSTGRES_USER: sky_scanner
       POSTGRES_PASSWORD: sky_scanner
       POSTGRES_DB: sky_scanner
     ports:
       - 5632:5432
     restart: unless-stopped
 
   back:
     build: skyScanner_back/.
     environment:
       - ENV
     command: npm run start:${ENV:-dev}
     ports:
       - 5100:5100
     depends_on:
       - postgres
 
  #  front:
  #    build: 
  #      context: skyScanner_front/.
  #    labels:
  #      SERVICE_CHECK_INTERVAL: 10s
  #    ports:
  #      - 3030:3030
  #    depends_on:
  #      - back

 
volumes:
  postgres_microservice_back:
